# Generated by Django 2.0.3 on 2018-05-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytul')),
                ('content', models.TextField(verbose_name='Tekst')),
                ('published', models.DateTimeField(auto_now=True, verbose_name='Data publikacji')),
                ('image', models.FileField(default=None, upload_to='images', verbose_name='Obrazy')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blogs')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Uzytkownik')),
                ('content', models.TextField(verbose_name='Tekst')),
                ('published', models.DateTimeField(auto_now=True, null=True, verbose_name='Data publikacji')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles')),
            ],
        ),
    ]
