# Generated by Django 2.0.5 on 2018-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180526_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/images/1.jpg', null=True, upload_to='images', verbose_name='Obrazy'),
        ),
    ]
