# Generated by Django 2.0.5 on 2018-05-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180526_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='images', verbose_name='Obrazy'),
        ),
    ]
