# Generated by Django 2.0.5 on 2018-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180601_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='isProtected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=150, verbose_name='Uzytkownik'),
        ),
    ]
