# Generated by Django 2.0.3 on 2018-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytul')),
                ('user', models.CharField(max_length=160, verbose_name='Uzytkownik')),
            ],
        ),
    ]
